spring.application.name=team-budget-backend

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.h2.console.settings.trace=true
spring.h2.console.settings.web-admin-password=97f2e11575d307b6844c642d26c206ab61cd8f6eae12d0e6949c7ed0452636c45fe4a5c06cf549b30e2c54637745397cbc1cf51480019e4cd2527f5edb8bfeea

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver

spring.web.resources.add-mappings=true

spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false
